const actions = {
  GET_DASHBOARD_DATA_START: 'GET_DASHBOARD_DATA_START',
  GET_DASHBOARD_DATA_SUCCESS: 'GET_DASHBOARD_DATA_SUCCESS',
  GET_DASHBOARD_DATA_FAILED: 'GET_DASHBOARD_DATA_FAILED',

  CREATE_CONNECTION_TCP_START: 'CREATE_CONNECTION_TCP_START',
  CREATE_CONNECTION_TCP_SUCCESS: 'CREATE_CONNECTION_TCP_SUCCESS',
  CREATE_CONNECTION_TCP_FAILED: 'CREATE_CONNECTION_TCP_FAILED',

  RESET_LASTUPDATE_TIME: 'RESET_LASTUPDATE_TIME',

  CREATE_CONNECTION_WEBSOCKET_START: 'CREATE_CONNECTION_WEBSOCKET_START',
  CREATE_CONNECTION_WEBSOCKET_SUCCESS: 'CREATE_CONNECTION_WEBSOCKET_SUCCESS',
  CREATE_CONNECTION_WEBSOCKET_FAILED: 'CREATE_CONNECTION_WEBSOCKET_FAILED',

  RECEIVE_DATA_TCP: 'RECEIVE_DATA_TCP',

  AUTH_START: 'AUTH_START',
  AUTH_FAILED: 'AUTH_FAILED',
  AUTH_SUCCESS: 'AUTH_SUCCESS',
  AUTH_OUT: 'AUTH_OUT',
  AUTH_ERROR_CONFIRM: 'AUTH_ERROR_CONFIRM',
  AUTH_REGISTER: 'AUTH_REGISTER',
  AUTH_REGISTER_SUCCESS: 'AUTH_REGISTER_SUCCESS',

  GET_MO_START: 'GET_MO_START',
  GET_MO_SUCCESS: 'GET_MO_SUCCESS',
  GET_MO_FAILED: 'GET_MO_FAILED',

  GET_PRODUCT_START: 'GET_PRODUCT_START',
  GET_PRODUCT_SUCCESS: 'GET_PRODUCT_SUCCESS',
  GET_PRODUCT_FAILED: 'GET_PRODUCT_FAILED',

  GET_WO_START: 'GET_WO_START',
  GET_WO_SUCCESS: 'GET_WO_SUCCESS',
  GET_WO_FAILED: 'GET_WO_FAILED',

  GET_BOM_START: 'GET_BOM_START',
  GET_BOM_SUCCESS: 'GET_BOM_SUCCESS',
  GET_BOM_FAILED: 'GET_BOM_FAILED',

  GET_MO_VALUE_START: 'GET_MO_VALUE_START',
  GET_MO_VALUE_SUCCESS: 'GET_MO_VALUE_SUCCESS',
  GET_MO_VALUE_FAILED: 'GET_MO_VALUE_FAILED',

  GET_WO_VALUE_START: 'GET_WO_VALUE_START',
  GET_WO_VALUE_SUCCESS: 'GET_WO_VALUE_SUCCESS',
  GET_WO_VALUE_FAILED: 'GET_WO_VALUE_FAILED',
};

export default actions;
